// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxqwddF8iJwhi4audaZOjQO4G1Ga9jmBo',
    appId: '1:1062824973534:android:06ba368889113958445e4f',
    messagingSenderId: '1062824973534',
    projectId: 'xpress-ee4f6',
    databaseURL: 'https://xpress-ee4f6-default-rtdb.firebaseio.com',
    storageBucket: 'xpress-ee4f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyu3Bmtv5n4B4GQpz_TKm_vioHkZ5D9ME',
    appId: '1:1062824973534:ios:f6e4c8c824fd67d0445e4f',
    messagingSenderId: '1062824973534',
    projectId: 'xpress-ee4f6',
    databaseURL: 'https://xpress-ee4f6-default-rtdb.firebaseio.com',
    storageBucket: 'xpress-ee4f6.appspot.com',
    iosClientId: '1062824973534-dhh4mk2tjl5o7crqd3u2836v530igt2g.apps.googleusercontent.com',
    iosBundleId: 'com.xpress.health',
  );
}
