// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGQ0FH-ZfLHbBs9jnsMspi_PWhEZanBQA',
    appId: '1:1062824973534:web:d6f020475a6cb3d2445e4f',
    messagingSenderId: '1062824973534',
    projectId: 'xpress-ee4f6',
    authDomain: 'xpress-ee4f6.firebaseapp.com',
    databaseURL: 'https://xpress-ee4f6-default-rtdb.firebaseio.com',
    storageBucket: 'xpress-ee4f6.appspot.com',
    measurementId: 'G-Z49FJFNWJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxqwddF8iJwhi4audaZOjQO4G1Ga9jmBo',
    appId: '1:1062824973534:android:0bdfb06b507e0c45445e4f',
    messagingSenderId: '1062824973534',
    projectId: 'xpress-ee4f6',
    databaseURL: 'https://xpress-ee4f6-default-rtdb.firebaseio.com',
    storageBucket: 'xpress-ee4f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyu3Bmtv5n4B4GQpz_TKm_vioHkZ5D9ME',
    appId: '1:1062824973534:ios:1cd8ff8e02a4fb39445e4f',
    messagingSenderId: '1062824973534',
    projectId: 'xpress-ee4f6',
    databaseURL: 'https://xpress-ee4f6-default-rtdb.firebaseio.com',
    storageBucket: 'xpress-ee4f6.appspot.com',
    iosClientId: '1062824973534-3lav7j8sqsip463a20m4evfbqt37hjp1.apps.googleusercontent.com',
    iosBundleId: 'com.intersmart.xpresshealthdev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyu3Bmtv5n4B4GQpz_TKm_vioHkZ5D9ME',
    appId: '1:1062824973534:ios:9c3d29f1e0e48151445e4f',
    messagingSenderId: '1062824973534',
    projectId: 'xpress-ee4f6',
    databaseURL: 'https://xpress-ee4f6-default-rtdb.firebaseio.com',
    storageBucket: 'xpress-ee4f6.appspot.com',
    iosClientId: '1062824973534-4fkvihfn0pm88tr69394essdd4o0af9s.apps.googleusercontent.com',
    iosBundleId: 'com.intersmart.xpress',
  );
}
